config/routes.rb
Socialbeam::Application.routes.draw do

  resources :users do |user|
    resources :messages do
      collection do
        post 'delete_multiple'
      end
    end
  end
  resource :socialbeams do
    collection do
        get 'home'
        get 'loadmorescribbles'
      end
  end
  resources :scribbles do
      resources :scribble_comments
  end
  resources :newsfeeds
  resources :sessions
  root :to => 'socialbeams#home'

  get "logout_user" => "sessions#destroy", :as => "logout_user"
  post "login_user" => "sessions#new", :as => "login_user"

 
  get  "refresh"  => "socialbeams#refreshscribbles", :as => "refresh"
  get "votedup"  => "socialbeams#votedup", :as => "votedup"
  get  "voteddown"  => "socialbeams#voteddown", :as => "voteddown"

  get "signup" => "users#new", :as => "signup"
  match "myconnections/:beamer_id" => "users#showconnections", :as => "myconnections"
  match "users/:beamer_id" => "users#show" , :as => 'profile'

  resources :friendships do
    collection do
      get 'req',:as=>"addfriend"
      get 'accept',:as=>"accept_fr"
      get 'reject',:as=>"reject_fr"
    end
  end

end

app/models/message.rb
class Message < ActiveRecord::Base
	
	attr_accessible :subject, :body, :sender_id, :recepient_id, :read_at,:sender_deleted,:recepient_deleted
	validates_presence_of :subject, :message => "Please enter message title"

	belongs_to :sender,
	:class_name => 'User',
	:primary_key => 'beamer_id',
	:foreign_key => 'sender_id'
	
	belongs_to :recepient,
	:class_name => 'User',
	:primary_key => 'beamer_id',
	:foreign_key => 'recepient_id'

    # marks a message as deleted by either the sender or the recepient, which ever the user that was passed is.
    # When both sender and recepient marks it deleted, it is destroyed.
    def mark_message_deleted(id,beamer_id)
    	self.sender_deleted = true if self.sender_id == beamer_id and self.id=id
    	self.recepient_deleted = true if self.recepient_id == beamer_id and self.id=id
    	self.sender_deleted && self.recepient_deleted ? self.destroy : save!
    end

    # Read message and if it is read by recepient then mark it is read
    def self.readingmessage(id, reader)
    	message = find(id, :conditions => ["sender_id = ? OR recepient_id = ?", reader, reader])
    	if message.read_at.nil? && (message.recepient.beamer_id==reader)
    		message.read_at = Time.now
    		message.save!
    	end
    	message
    end

    # Based on if a message has been read by it's recepient returns true or false.
    def read?
    	self.read_at.nil? ? false : true
    end


end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  
  before_filter :set_user
  
  def index
    if params[:mailbox] == "sent"
      @messages = @user.sent_messages
    elsif params[:mailbox] == "inbox"
      @messages = @user.received_messages
    #elsif params[:mailbox] == "archieved"
     # @messages = @user.archived_messages
    end
  end
  
  def new
    @message = Message.new
    if params[:reply_to]
      @reply_to = User.find_by_beamer_id(params[:reply_to])
      unless @reply_to.nil?
        @message.recepient_id = @reply_to.beamer_id
      end
    end
  end
  
  def create
    @message = Message.new(params[:message])
    @message.sender_id = @user.beamer_id
    if @message.save
      flash[:notice] = "Message has been sent"
      redirect_to user_messages_path(current_user, :mailbox=>:inbox)
    else
      render :action => :new
    end
  end

  def show
    @message = Message.readingmessage(params[:id],@user.beamer_id)
  end
  
  def delete_multiple
      if params[:delete]
        params[:delete].each { |id|
          @message = Message.find(id)
          @message.mark_message_deleted(@message.id,@user.beamer_id) unless @message.nil?
        }
        flash[:notice] = "Messages deleted"
      end
      redirect_to user_messages_path(@user, @messages)
  end
  
  private
    def set_user
      @user = current_user
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_inbox.html.erb
<h2>Your Inbox</h2>
<% if @messages.size == 0 %>
No messages in your Inbox
<% else %>
		<%= form_tag delete_multiple_user_messages_path, :method=>:post do %>
			<table  class="table table-bordered">
			        <tr>
					<th>Delete?</th>
					<th>Sent</th>
					<th>Sender</th>
					<th>Sent</th>
				</tr>
					<% for message in @messages %>
						<tr>
							<td><%= check_box_tag "delete[]", message.id %></td>
							<td>
								<% if message.read? %>
								  <%= link_to h(message.subject), user_message_path(@user, message) %>
								<% else %>
								  <%= link_to "#{h(message.subject)} (unread)", user_message_path(@user, message) %>
								<% end %>
							</td>
							<td><%= "#{message.sender.first_name} #{message.sender.last_name}" %></td>
					        <td><%=h message.created_at.to_s(:long) %></td>
						</tr>
			<% end %>
			</table>
		<%= submit_tag "Delete selected", :class => "btn btn-danger"  %> |
		<% end %>
<%= link_to "Compose New Message", new_user_message_path(@user)%> | 
<%= link_to "View Sent Messages", user_messages_path(current_user, :mailbox => :sent)%>
<% end %>

app/views/messages/_sent.html.erb
<h2>Sent Messages</h2>
<% if @messages.size == 0 %>
No Sent messages
<% else %>
		<%= form_tag delete_multiple_user_messages_path, :method=>:post do %>
			<table class="table table-bordered">
				<tr>
					<th>Delete?</th>
					<th>Subject</th>
					<th>Send To</th>
					<th>Sent At</th>
				</tr>
				<% for message in @messages %>
				<tr>
					<td><%= check_box_tag "delete[]", message.id %></td>
					<td><%= link_to h(message.subject), user_message_path(@user, message) %></td>
					<td><%= "#{message.recepient.first_name} #{message.recepient.last_name}" %></td>
					<td><%=h message.created_at.to_s(:long) %></td>
				</tr>
				<% end %>
			</table>
		<%= submit_tag "Delete selected" %>
		<% end %>
	<%= link_to "View Inbox", user_messages_path(current_user, :mailbox=>:inbox)%>
<% end %>

app/views/messages/index.html.erb
<% if params[:mailbox] == "sent" %>
      <%= render :partial => "sent" %>
  <% elsif params[:mailbox] == "inbox" %>
      <%= render :partial => "inbox" %>
  <% elsif params[:mailbox] == "archieved" %>
          <%= render :partial => "inbox" %>
  <% end %>

app/views/messages/new.html.erb
<%= form_for @message, :url => user_messages_path(@user) do |f| %>
  <% if @message.recepient_id.nil? %>
    <p>
      To:<br />
      <%= f.text_field :recepient_id %>
    </p>
  <% else %>
    <p>
      To:<br />
      <%= f.text_field :recepient_id, :value=>@message.recepient_id,:readonly => true %>
    </p>
  <% end %>
      <p>
        Subject:<br />
        <%= f.text_field :subject %>
      </p>
      <p>
        Message<br />
        <%= f.text_area :body %>
      </p>

      <%= submit_tag "Send", :class => "btn btn-primary" %>
<% end %>

app/views/messages/show.html.erb
<p>
	<strong>From:</strong> 
	<%= @message.sender == @user ? "You" : "#{@message.sender.first_name} #{@message.sender.last_name}" %>
</p>

<p>
	<strong>Received:</strong> 
	<%= @message.created_at.to_s(:long) %>
</p>
<p>
	<strong>To:</strong> 
	<%= @message.recepient == @user ? "You" : "#{@message.recepient.first_name} #{@message.recepient.last_name}" %>
</p>

<p>
	<strong>Message</strong><br />
	<%=h @message.body %>
</p>
<p>
	<% if @message.recepient == @user %>
	<%= link_to "Reply", new_user_message_path(@user, :reply_to => @message.sender.beamer_id) %> |
	<% end %>
	<%= link_to "Inbox", user_messages_path(current_user, :mailbox=>:inbox)%>
</p>