config/routes.rb
Socialbeam::Application.routes.draw do

  resources :users do |user|
    resources :messages do
      collection do
        post 'delete_multiple'
      end
    end
  end
  resource :socialbeams do
    collection do
        get 'home'
        get 'loadmorescribbles'
      end
  end
  resources :scribbles do
      resources :scribble_comments
  end
  resources :newsfeeds
  resources :sessions
  root :to => 'socialbeams#home'

  get "logout_user" => "sessions#destroy", :as => "logout_user"
  post "login_user" => "sessions#new", :as => "login_user"

 
  get  "refresh"  => "socialbeams#refreshscribbles", :as => "refresh"
  get "votedup"  => "socialbeams#votedup", :as => "votedup"
  get  "voteddown"  => "socialbeams#voteddown", :as => "voteddown"

  get "signup" => "users#new", :as => "signup"
  match "myconnections/:beamer_id" => "users#showconnections", :as => "myconnections"
  match "users/:beamer_id" => "users#show" , :as => 'profile'

  resources :friendships do
    collection do
      get 'req',:as=>"addfriend"
      get 'accept',:as=>"accept_fr"
      get 'reject',:as=>"reject_fr"
    end
  end

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
	attr_accessible :status,:user,:friend
	belongs_to :user,:foreign_key=>"beamer_id",:primary_key=>"beamer_id"
	belongs_to :friend, :class_name => "User",:primary_key=>"beamer_id",:foreign_key => "friend_beamer_id"
	validates_presence_of :friend_beamer_id, :beamer_id

	def self.are_friends(user, friend)
		return false if user == friend
		return true unless find_by_beamer_id_and_friend_beamer_id_and_status(user,friend,"accepted").nil?
		return true unless find_by_beamer_id_and_friend_beamer_id_and_status(friend,user,"accepted").nil?
		false
	end

	def self.are_friends_pending(user, friend)
		return false if user == friend
		return true unless find_by_beamer_id_and_friend_beamer_id_and_status(user,friend,"pending").nil?
		return true unless find_by_beamer_id_and_friend_beamer_id_and_status(friend,user,"requested").nil?
		false
	end

	def self.request(user, friend)
		return false if are_friends(user, friend)
		return false if user == friend
		f1 = new(:user => user, :friend => friend, :status => "pending")
		f2 = new(:user => friend, :friend => user, :status => "requested")
		transaction do
			f1.save
			f2.save
		end
	end

	def self.accept(user, friend)
		f1 = find_by_beamer_id_and_friend_beamer_id(user.beamer_id, friend.beamer_id)
		f2 = find_by_beamer_id_and_friend_beamer_id(friend.beamer_id, user.beamer_id)
		if f1.nil? or f2.nil?
			return false
		else
			transaction do
				f1.update_attributes(:status => "accepted")
				f2.update_attributes(:status => "accepted")
			end
		end
		return true
	end

	def self.reject(user, friend)
		f1 = find_by_beamer_id_and_friend_beamer_id(user.beamer_id, friend.beamer_id)
		f2 = find_by_beamer_id_and_friend_beamer_id(friend.beamer_id, user.beamer_id)
		if f1.nil? or f2.nil?
			return false
		else
			transaction do
				f1.destroy
				f2.destroy
				return true
			end
		end
	end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def req
    @user = current_user
    @friend = User.find_by_beamer_id(params[:beamer_id])
    unless @friend.nil?
      if Friendship.request(@user, @friend)
        flash[:notice] = "Friendship with #{@friend.full_name} requested"
      else
        flash[:notice] = "Friendship with #{@friend.full_name} cannot be requested"
      end
    end
    redirect_to :back
  end

  def accept
    @user = current_user
    @friend = User.find_by_beamer_id(params[:beamer_id])
    unless @friend.nil?
      if Friendship.accept(@user, @friend)
        flash[:notice] = "Friendship with #{@friend.full_name} accepted"
      else
        flash[:notice] = "Friendship with #{@friend.full_name} cannot be accepted"
      end
    end
    redirect_to :back
  end

  def reject
    @user = current_user
    @friend = User.find_by_beamer_id(params[:beamer_id])
    unless @friend.nil?
      if Friendship.reject(@user, @friend)
        flash[:notice] = "Friendship with #{@friend.full_name} rejected"
      else
        flash[:notice] = "Friendship with #{@friend.full_name} cannot be rejected"
      end
    end
    redirect_to :back
  end

end

app/views/friendships/_all_connections.html.erb
<h2>Beamers in Socialbeam</h2>
<div>	
	<ul>
		<% all_connections.each do |beamer| %>
		<% unless beamer==current_user %>
		<li>
			<%= link_to "#{beamer.first_name} #{beamer.last_name}", user_path(beamer.beamer_id) %>
				<% if Friendship.are_friends(current_user.beamer_id,beamer.beamer_id) %>
				 <label class="label">Friend</label>
				<% else %>
				 <%= link_to "Add Friend",addfriend_friendships_path(:beamer_id => beamer.beamer_id) %>
			<% end %>
			<% end %>
		</li>	
		<% end %>
	</ul>
</div>

app/views/friendships/_friendrequests.html.erb
<h2>Friend Requests</h2>
<ol>
	<% @user.requested_friends.each do |friend| %>
	<li>
		<%=link_to "#{friend.full_name}",user_path(friend.beamer_id) %> 
		<%= link_to "Accept",accept_fr_friendships_path(:beamer_id =>friend.beamer_id) %> |
		<%= link_to "Reject",reject_fr_friendships_path(:beamer_id =>friend.beamer_id) %>
	</li>
	<% end %>
</ol>

app/views/friendships/_friends.html.erb
<h2>Your Friends</h2>
<tr>
	<% @user.friends.each do |friend| %>
	<%=link_to "#{friend.full_name}",user_path(friend.beamer_id) %> 
	<% end %>
</tr>
<div class='socialbeam_books'>  

	<div class="sbook_cover" id="friends_page">

		<div class="sbook_pages" style="left: 3px; width: 862px;box-shadow:0 1px 5px 0 #0A2851"></div>
		<div class="sbook_pages" style="left: 5px; width: 858px;"></div>
		<div class="sbook_pages" style="left: 7px; width: 854px;"></div>
		<div id="friend_page_rows" class="sbook_pages" style="left: 9px; width: 850px;">
			<div class="sbpage_left">
				<div class="friends_message">Click On a Letter To Load Friends</div>
			</div>
			<div class="sbpage_bind"><span class="top"></span><span class="bottom"></span></div>
			<div class="sbpage_right"></div>

		</div>
	</div> 
	<div  id="startup_page">
		<div class="sb_cover_outer">

			<div class="sb_cover_letters">
				<div class="sb_cover_letter">A</div>
				<div class="sb_cover_letter" style="background: #8791d9;">B</div>
				<div class="sb_cover_letter" style="background: #3bcbd0;">C</div>
				<div class="sb_cover_letter" style="background: #da5c83;">D</div>
			</div>

			<div class="sbook_cover_inner">
				<div class="sbook_cover_bar"></div>
				<div class="sbook_cover_img"><img src="/assets/sb_large.png" /></div>
				<div class="sbook_cover_title">Tweet Book</div>

				<div class="sb_cover_open"><div class="arrow_left"></div></div>
			</div>
		</div>
	</div>
	<div id="profile_page" class="sbook_cover">

		<div class="sbook_pages" style="left: 3px; width: 862px;box-shadow:0 1px 5px 0 #0A2851"></div>
		<div class="sbook_pages" style="left: 5px; width: 858px;"></div>
		<div class="sbook_pages" style="left: 7px; width: 854px;"></div>
		<div class="sbook_pages" style="left: 9px; width: 850px;">
			<div class="sbpage_left"></div>
			<div class="sbpage_bind"><span class="top"></span><span class="bottom"></span></div>
			<div class="sbpage_right"></div>
		</div>
	</div>


	<div class="letters">
		<div class="letter">A</div>
		<div class="letter" style="background: #8791d9;">B</div>
		<div class="letter" style="background: #3bcbd0;">C</div>
		<div class="letter" style="background: #da5c83;">D</div>
	</div>
	<div class="sb_cover_close"><div class="arrow_right"></div></div>
</div>

</div>

<script>
$(document).ready(function(){

	$("#profile_page").hide();
	$("#friends_page").hide();

	$(".tb_cover_open").live("click",function(){
		$("#startup_page").fadeOut("slow");
		$("#friends_page").fadeIn("slow");
		$(".letters").css("display","block");
		$(".tb_cover_close").css("display","block");

	});
	$(".sb_cover_open").live("click",function(){
		$("#startup_page").fadeOut("slow");
		$("#friends_page").fadeIn("slow");
		$(".letters").css("display","block");
		$(".sb_cover_close").css("display","block");

	});
	$(".sb_cover_close").live("click",function(){
            $("#friends_page").fadeOut("slow");
            $("#profile_page").fadeOut("slow");
            $("#startup_page").fadeIn("slow");
            $(".letters").css("display","none");
            $(".sb_cover_close").css("display","none");

        });
};
</script>

app/views/friendships/_friendspending.html.erb
<h2>Friend Pending</h2>
<ol>
	<% @user.pending_friends.each do |friend| %>
	<li>
		<%=link_to "#{friend.full_name}",user_path(friend.beamer_id) %> 
	</li>
	<% end %>
</ol>