config/routes.rb
Socialbeam::Application.routes.draw do

  resources :users do |user|
    resources :messages do
      collection do
        post 'delete_multiple'
      end
    end
  end
  resource :socialbeams do
    collection do
        get 'home'
        get 'loadmorescribbles'
      end
  end
  resources :scribbles do
      resources :scribble_comments
  end
  resources :newsfeeds
  resources :sessions
  root :to => 'socialbeams#home'

  get "logout_user" => "sessions#destroy", :as => "logout_user"
  post "login_user" => "sessions#new", :as => "login_user"

 
  get  "refresh"  => "socialbeams#refreshscribbles", :as => "refresh"
  get "votedup"  => "socialbeams#votedup", :as => "votedup"
  get  "voteddown"  => "socialbeams#voteddown", :as => "voteddown"

  get "signup" => "users#new", :as => "signup"
  match "myconnections/:beamer_id" => "users#showconnections", :as => "myconnections"
  match "users/:beamer_id" => "users#show" , :as => 'profile'

  resources :friendships do
    collection do
      get 'req',:as=>"addfriend"
      get 'accept',:as=>"accept_fr"
      get 'reject',:as=>"reject_fr"
    end
  end

end

app/models/scribble.rb
class Scribble < ActiveRecord::Base
  # attr_accessible :title, :body
  include Scrubber

  attr_accessible :post, :posted_by, :posted_by_uid, :scribble_id

  before_save :create_scribble_id
  
  has_many :posted_comments,
  :class_name => 'ScribbleComment',
  :primary_key=>'scribble_id',
  :foreign_key => 'scribble_id',
  :order => "scribble_comments.created_at DESC"

  def create_scribble_id
    self.scribble_id=gen_scribble_id
  end

end

app/models/scribbles.rb
class Scribbles < ActiveRecord::Base
  
  attr_accessible :post, :posted_by, :posted_by_uid

end

app/controllers/scribbles_controller.rb
class ScribblesController < ApplicationController
  # GET /scribbles
  # GET /scribbles.json
  
  def index
    @scribbles = Scribble.find(:all, :order => 'scribbles.created_at DESC')
      respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @scribbles }
    end
  end

  # GET /scribbles/1
  # GET /scribbles/1.json
  def show
    @scribble = Scribble.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @scribble }
    end
  end

  # GET /scribbles/1/edit
  def edit
    @scribble = Scribble.find(params[:id])
  end

  # POST /scribbles
  # POST /scribbles.json
  def create
    @scribble = Scribble.new(params[:scribble])
    @scribble.posted_by_uid=current_user.beamer_id
    @scribble.posted_by=current_user.first_name+" "+current_user.last_name
    @scribble.ups=0
    @scribble.downs=0
 
    respond_to do |format|
      if @scribble.save!
        format.html { redirect_to root_path }
        format.json { render :json => @scribble, :status => :created, :location => @scribble }
      else
        format.html { redirect_to root_path }
        format.json { render :json => @scribble.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /scribbles/1
  # PUT /scribbles/1.json
  def update
    @scribble = Scribble.find(params[:id])

    respond_to do |format|
      if @scribble.update_attributes(params[:scribble])
        format.html { redirect_to @scribble, :notice => 'Scribble was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @scribble.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /scribbles/1
  # DELETE /scribbles/1.json
  def destroy
    @scribble = Scribble.find(params[:id])
    @scribble.destroy

    respond_to do |format|
      format.html { redirect_to scribbles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/scribbles_helper.rb
module ScribblesHelper
end

app/views/scribbles/_form.html.erb
<%= form_for(@scribble) do |f| %>
  <% if @scribble.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scribble.errors.count, "error") %> prohibited this scribble from being saved:</h2>

      <ul>
      <% @scribble.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scribbles/_from.html.erb
<%= form_for(@scribble) do |f| %>
  <% if @scribble.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scribble.errors.count, "error") %> prohibited this scribble from being saved:</h2>

      <ul>
      <% @scribble.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post %><br />
    <%= f.text_field :post %>
  </div>
  <div class="field">
    <%= f.label :posted_by %><br />
    <%= f.text_field :posted_by %>
  </div>
  <div class="field">
    <%= f.label :posted_by_uid %><br />
    <%= f.number_field :posted_by_uid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scribbles/_new.html.erb
<%= form_for(@scribble) do |f| %>
<div class="field">
    <%= f.label :post %><br />
    <%= f.text_field :post %>
  </div>
<div class="actions" id="refreshscribbles">
    <%= f.submit("Scribble it") %>
  </div>
<% end %>

app/views/scribbles/_newscribble.html.erb
<%= form_for(@scribble) do |f| %>
<div class="">
	<div class="field">
		<%= f.text_area :post,:rows=>3,:placeholder=>"What's on your mind,#{current_user.first_name}?",
		:class=>"sribble-status-text"
		%>
	</div>
	<div class="sribble-status-actions" id="refreshscribbles">
		<%= f.submit "Share",:class=>"btn btn-info" %>
	</div>
</div>
<% end %>

app/views/scribbles/_scribbles.html.erb

<% if scribbles_streams.empty? %>
<h3> no scribbles yet </h3>
<% else %>
<% scribbles_streams.each do |scribble| %>
<div class="scribblebody" id="<%=scribble.scribble_id %>"> 
  <div class="scribbleimg"><%=image_tag 'default_avatar.png' %></div>
  <div class="scribbletext">
    <blockquote>
      <p><%= scribble.post %></p>
      <small><%= scribble.posted_by %></small>
    </blockquote>
    <div class="scribbletime">
      <label class="label">posted <%= TimelineBeautify.beauty_time(scribble.created_at) %></label>
      <label class="label"><%= scribble.posted_comments.count %> comments</label>
      <a href="" id="<%= scribble.id %>" name="up" class="votes">
        <i class="icon-thumbs-up"></i><%= scribble.ups %> likes</a>

        <a href=""  id="<%= scribble.id %>"  name="down" class="votes">
          <i class="icon-thumbs-down"></i><%= scribble.downs %> dislikes</a>
        </div>
      </div>
        <%= render :partial=>"scribble_comments/newcomment",:locals=>{:scribble=>scribble} %>
        <%= render :partial=>"scribble_comments/postedcomments",:locals=>{:scribble=>scribble} %>
      
    </div>
    <% end %>
<% end %>

app/views/scribbles/edit.html.erb
<h1>Editing scribble</h1>

<%= render 'form' %>

<%= link_to 'Show', @scribble %> |
<%= link_to 'Back', scribbles_path %>

app/views/scribbles/index.html.erb
<h1>Listing scribbles</h1>

<table>
  <tr>
    <th>Post</th>
    <th>Posted by</th>
    <th>Posted by uid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @scribbles.each do |scribble| %>
  <tr>
    <td><%= scribble.post %></td>
    <td><%= scribble.posted_by %></td>
    <td><%= scribble.posted_by_uid %></td>
    <td><%= link_to 'Show', scribble %></td>
    <td><%= link_to 'Edit', edit_scribble_path(scribble) %></td>
    <td><%= link_to 'Destroy', scribble, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Scribble', new_scribble_path %>

app/views/scribbles/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_scribble_path(@scribble) %> |
<%= link_to 'Back', scribbles_path %>