config/routes.rb
Socialbeam::Application.routes.draw do

  resources :users do |user|
    resources :messages do
      collection do
        post 'delete_multiple'
      end
    end
  end
  resource :socialbeams do
    collection do
        get 'home'
        get 'loadmorescribbles'
      end
  end
  resources :scribbles do
      resources :scribble_comments
  end
  resources :newsfeeds
  resources :sessions
  root :to => 'socialbeams#home'

  get "logout_user" => "sessions#destroy", :as => "logout_user"
  post "login_user" => "sessions#new", :as => "login_user"

 
  get  "refresh"  => "socialbeams#refreshscribbles", :as => "refresh"
  get "votedup"  => "socialbeams#votedup", :as => "votedup"
  get  "voteddown"  => "socialbeams#voteddown", :as => "voteddown"

  get "signup" => "users#new", :as => "signup"
  match "myconnections/:beamer_id" => "users#showconnections", :as => "myconnections"
  match "users/:beamer_id" => "users#show" , :as => 'profile'

  resources :friendships do
    collection do
      get 'req',:as=>"addfriend"
      get 'accept',:as=>"accept_fr"
      get 'reject',:as=>"reject_fr"
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= "Socialbeam" %></title>
   <!-- Javascripts
   ================================================== -->
   <%= javascript_include_tag :jquery %>
   <%= javascript_include_tag :bootstrap %>
   <%= javascript_include_tag :modernizer %>
   <!-- stylesheets
   ================================================== -->
   <%= stylesheet_link_tag    "application" %>
   <%= csrf_meta_tags %>

   <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
      <![endif]-->
    </head>
    <body>
     <!-- Log In Modal -->
     <div class="modal hide fade" id="login" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Log in to Socialbeam</h3>
      </div>
      <div class="modal-body">
        <%= render "/sessions/new.html.erb"%>
      </div>
      <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
      </div>
    </div>
    <!-- End of Log In Modal -->

    <!-- Sign Up Modal -->
<!--    <div class="modal hide fade" id="signup" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Create an Account</h3>
      </div>
      <div class="modal-body">
        <%# @user = User.new %>
        <%#= render "/users/new.html.erb"%>
      </div>
      <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
      </div>
    </div> -->
    <%#= render :partial => "layouts/signup" %>
    <!-- End of Sign Up Modal -->


    <% if current_user %>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<%= root_url %>">
+          <%= image_tag("sb_large.png", :class => "brandimage")%>
+        </a>
          <div class="nav-collapse">
            <ul class="nav">
              <li><a href="<%= root_url %>"><i class="icon-home"></i>Home</a></li>
              <li class="divider-vertical"></li>
              <li><a href="<%= profile_path(current_user.beamer_id)%>"><i class="icon-user"></i>Profile</a></li>
              <li class="divider-vertical"></li>
              <li><a href="<%= myconnections_path(current_user.beamer_id)%>"><i class="icon-book"></i>My Connections</a></li>
              <li class="divider-vertical"></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-folder-close"></i>Messaging<b class="caret"></b></a>
                <ul class="dropdown-menu">
                 <li class="nav-header">Private</li>
                 <li><%= link_to "Compose New", new_user_message_path(current_user)%></li>
                 <li><%= link_to "Inbox", user_messages_path(current_user, :mailbox=>:inbox)%></li>
                 <li><%= link_to "Sent", user_messages_path(current_user, :mailbox => :sent)%></li>
                 <li><%= link_to "Archieved", user_messages_path(current_user, :mailbox => :archieved)%></li>
                 <li class="divider"></li>
                 <li class="nav-header">Groups</li>
                 <li><a href="#">Create New</a></li>
                 <li><a href="#">Inbox</a></li>
                 <li><a href="#">Sent Items</a></li>
               </ul>
             </li>
             <li class="divider-vertical"></li>
           </ul>
           <form class="navbar-search pull-left" action="">
            <input type="text" class="search-query span2" placeholder="Search">
          </form>
          <ul class="nav pull-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-briefcase"></i>Account<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Settings</a></li>
                <li><a href="#">Security</a></li>
                <li><a href="#">Permission</a></li>
                <li class="divider"></li>
                <li><a href="/logout_user">Logout(<%= current_user.first_name %>)</a></li>
              </ul>
            </li>
          </ul>
        </div><!-- /.nav-collapse -->
      </div><!-- container-->
    </div><!-- /navbar-inner -->
  </div><!-- /navbar -->
  <% else %>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="<%= root_url %>">
+          <%= image_tag("sb_large.png", :class => "brandimage")%>
+        </a>

        <div class="nav-collapse">

          <ul class="nav pull-right">
            <button class="btn btn-info" id="loginclick"><i class="icon-beer"></i> Sign In</button>
            <li class="divider-vertical"></li>
            <a class="btn btn-info" href="<%= new_user_path %>"><i class="icon-coffee"></i> Join Socialbeam</a>
            <li class="divider-vertical"></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Why Join Socialbeam?<b class="caret"></b></a>
              <ul class="dropdown-menu">
               <li><a href="#">Connect</a></li>
               <li><a href="#">Collaborate</a></li>
               <li><a href="#">Empower</a></li>
               <li class="divider"></li>
               <li><a href="#">Take A Tour!</a></li>
             </ul>
           </li>
         </ul>
       </div><!-- /.nav-collapse -->
     </div><!-- container> -->
   </div><!-- /navbar-inner -->
 </div><!-- /navbar -->
 <% end %>
 <% if current_user %>
 <div class="container" style="margin-top:50px;">
  <%= yield %>
  <footer>
    <p>&copy; Socialbeam 2012</p>
  </footer>
</div> <!-- /container -->
<% else %>
<div class="container" style="margin-top:50px;">
  <%= yield %>
  <footer>
    <p>&copy; Socialbeam 2012</p>
  </footer>
</div> <!-- /container -->
<% end %>
</body>
<script>
$('#loginclick').click(function(){
  $('#login').modal('show')
});
/*$('#signupclick').click(function(){
  $('#signup').modal('show')
});*/
</script>
</html>